name: Bicep What if deployment
on:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Azure CLI
        uses: Azure/cli@v1.0.9
        with:
          inlineScript: true
          
      - name: Install az bicep
        run: az bicep install

      - name: Login to Azure
        run: az login --service-principal --username ${{ secrets.AZURE_SP_APP_ID }} --password ${{ secrets.AZURE_SP_PASSWORD }} --tenant ${{ secrets.AZURE_TENANT_ID }}

      - name: Azure Deployment
        run: |
          # Add your deployment commands here
          # For example:
          # az account set --subsciption {subscriptionID}
          # az deployment group what-if --resource-group {rgName} --name {deploymentName} --template-file main.bicep --parameters main.bicepparam

